# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create a new app in App Store Connect"
  lane :create_new_app do
    create_app_online(
      app_identifier: "com.clever.lifestyle",
      app_name: "Clever - Cycle Tracker",
      app_version: "1.0",
      sku: "CLEVER-2024",
      language: "English",
      team_id: "W3N4W6AVQA",
      itc_team_id: "123281569"
    )
  end

  desc "Build and upload to TestFlight with public link"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "8ADBXLN97S",
      issuer_id: "89f06065-abc3-4944-b620-bbf05d7f174b",
      key_filepath: "fastlane/real_ser.p8"
    )
    
    # Build app using build_app (like in diwo)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    
    # Upload to TestFlight (build_app automatically creates IPA)
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: false,
      distribute_external: true,
      notify_external_testers: true,
      beta_app_feedback_email: "vseznayka@mail.ru",
      beta_app_description: "Clever - Mobile app for understanding menstrual cycles"
    )
    
    UI.success("Build uploaded to TestFlight!")
    UI.important("To enable public beta testing:")
    UI.important("1. Go to App Store Connect")
    UI.important("2. Select your app -> TestFlight")
    UI.important("3. Enable 'Public Link' in the External Testing section")
  end
end

